### ISSUE TITLE
Generowanie JPK_FA

### ISSUE THREAD

**Issue by IntinteDAO** [lkosson/profak#1]
Witam

Mój ojciec potrzebuje programu do fakturowania. Znalazłem mu profak, ale nie potrafi wygenerować JPK_FA. Ja też się nie znam za bardzo na tym. Czy jest jakiś prosty tutorial jak to zrobić?

**Comment by lkosson** [comment]
Program nie daje możliwości generowania JPK_FA. Dostępny jest jedynie JPK_V7M.

Obsługa JPK_FA odeszła na dalszy plan ze względu na groźby rychłego wprowadzenia obowiązkowego KSeF dla wszystkich, czyniąc JPK_FA niepotrzebnym. Data pełnego wdrożenia KSeF przez MF została już kilkukrotnie przesunięta, a JPK_FA nie jest zbyt skomplikowanym formatem, więc w wolnej chwili dodam możliwość generowania tego zestawienia.

**Comment by lkosson** [comment]
Dodane w wersji 1.5.0.
