### ISSUE TITLE
Możliwość zarządzania kolumnami (ukrywanie kolumn)

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#10]
Cześć,

Czy istnieje szansa na wdrożenie możliwości ukrywania kolumn?
Przykładowy screen z innego programu, po kliknięciu prawym klawiszem myszy w pasek kolumn pojawia się menu kontekstowe gdzie można wybrać co ukrywamy:

![image](https://github.com/user-attachments/assets/8df1c2d7-0f7c-466c-9bf9-35ec0e0a9f64)

**Comment by lkosson** [comment]
Obecnie (od #6) zapamiętywana jest kolejność i szerokość kolumn, więc te nieinteresujące można przenieść gdzieś na koniec i/lub zwęzić do zera. Były plany zrobienia menu kontekstowego jak na screenie, ale rozbiły się o pewne problemy natury technicznej z .NET 8. Wrócę do tematu i sprawdzę co da się zrobić.

**Comment by lkosson** [comment]
Dodane w wersji 1.9.0.
