### ISSUE TITLE
Kategoria `Zapłacone`

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#11]
Cześć,

W menu możemy zobaczyć wszystkie faktury zakupowe i sprzedażowe. Możemy też skorzystać z kategorii `Do zapłaty`.
Czy jest możliwość dodania również kategorii `Zapłacone`?

Chyba powinno to być w tym miejscu, pod pozycją `Do zapłaty`.
![image](https://github.com/user-attachments/assets/e540a66c-8658-464c-8a0a-16cc840caf50)

**Comment by lkosson** [comment]
Ma sens. Dodam.

**Comment by lkosson** [comment]
W sumie to nie wiem czy faktycznie taki spis będzie użyteczny, ale mimo to dodałem go w wersji 1.9.0.

**Comment by kanlukasz** [comment]
> W sumie to nie wiem czy faktycznie taki spis będzie użyteczny, ale mimo to dodałem go w wersji 1.9.0.

Tak, generalnie logika w mojej głowie zawiodła, gdy wystawiłem ten ticket.

To miało by większy użytek, gdyby dało się odfiltrować konkretny miesiąc.
Ale to już jest wdrożone w drzewku menu ` + Według daty`.
Wystarczy, że przesortuje wg. kolumny `Zapł.` i uzyskuję listę niezapłaconych z konkretnego miesiąca i jest OK.

No nic, tak czy inaczej dzięki za dodanie, może jednak w przyszłości się okaże, że cała lista też się do czegoś przyda :-)
