### ISSUE TITLE
Dodanie metody każdej wpłaty

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#13]
Cześć,

Z doświadczenia wiem, że często klienci regulują faktury na różne sposoby.
lub faktury zakupowe są płacone w częściach i różnymi metodami.

Np 50% gotówką, a drugie 50% poszło przelewem, albo blikiem itd itd

Nasunęła mi się myśl, że fajnie by było mieć możliwość wpisania, jaką metodą płatności została uregulowana dana wpłata.
W tym miejscu:

![image](https://github.com/user-attachments/assets/033961f9-1db9-49f5-bf90-311fe30343ec)

Pewnie powinna to być lista select z ustalonymi metodami? Lub ręczny komentarz, ale to chyba ciężko będzie filtrować w przyszłości

**Comment by lkosson** [comment]
Ma sens. W programie, w którym rozliczam spółkę, dodałem to jako pole do swobodnego uzupełnienia - tutaj pewnie zrobię podobnie, jako pole "Uwagi" lub "Komentarz". Przyda się do odnotowywania wpłat z inną metodą płatności, kompensat lub alternatywnych numerów rachunków.

**Comment by lkosson** [comment]
Dodane w wersji 1.9.0.
