### ISSUE TITLE
Fizycznie położenie plików dołączanych do dokumentów i pobieranie

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#14]
Cześć,

Dodaje sobie do faktur jakieś pliki, np:
![image](https://github.com/user-attachments/assets/26b4b4e1-1a7c-49f4-ab91-16c00221b70e)

Gdzie potem mogę znaleźć te pliki fizycznie? Czy mogę wyznaczyć miejsce gdzie one mają się składować?

Może powiem o jaki workflow chodzi, to łatwiej będzie zobrazować sytuację:
- w ciągu miesiąca, dodaje jakieś tam faktury zakupowe.
- do każdej faktury dodaje jej skan `jpg` lub fakturę w `pdf` jako załącznik
- na koniec miesiąca chciałbym wszystkie te załączniki pobrać/skopiować dla mojej księgowości

Czy to jest możliwe?
Może w drzewku menu mogła by się pojawić nowa zakładka Pliki?

**Comment by lkosson** [comment]
Pliki są zapisywane jako bloby w bazie danych (ze wszystkimi tego konsekwencjami). Mam dokładnie taki sam workflow w "dużej" wersji programu i tam też dorabiałem dla własnej wygody zbiorcze eksportowanie załączników. Dodam to i w ProFaku.

**Comment by lkosson** [comment]
Dodane w wersji 1.9.0.
