### ISSUE TITLE
Kolumna `Pliki` na listingu faktur

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#15]
Cześć,

Czy jest szansa na dodanie kolumny `Pliki` na liście faktur?
Wtedy od razu łatwo można by sortować lub przeglądać, która faktura ma dołączone jakieś pliki
Coś w tym stylu jak kolumna `Zapł.`
![image](https://github.com/user-attachments/assets/9ca15079-c31e-4f59-973b-5a0414708b51)

**Comment by lkosson** [comment]
Tak. Dodam.

**Comment by lkosson** [comment]
Dodane w wersji 1.9.0.
