### ISSUE TITLE
Możliwośc eksportu do pdf kilku faktur jednocześnie

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#16]
Cześć,

Czy jest możliwość wydrukowania wszystkich wystawionych faktur w danym miesiącu?

Przykładowy scenariusz:
- kończy sie miesiąc
- wchodzę w Faktury -> wg. daty -> Listopad
- chcę wydrukować do PDF wszystkie faktury które wystawiłem, aby przekazać je do mojej księgowości

Próbowałem zaznaczyć wszystkie `Ctrl+A` i kliknąć `Drukuj`, ale to nie zadziałało.

**Comment by lkosson** [comment]
Powinno zadziałać. Na czym dokładnie polega problem?

**Comment by kanlukasz** [comment]
Sorry, faktycznie działa. Nie zwróciłem uwagi na stronicowanie w pdf
