### ISSUE TITLE
Polecenia SQL - większe okienko

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#17]
Cześć

Czy da radę zrobić pole `Treść polecenia` SQL dłuższe?
3 linijki na kwerendę troszkę za mało ;-) A scroll też nie działa.

![image](https://github.com/user-attachments/assets/4864920d-ae82-40e3-a98b-84fdfeaf1af9)

Z góry dzięki

**Comment by lkosson** [comment]
Jasne - zmienię.

**Comment by lkosson** [comment]
Poprawione w wersji 1.9.0.
