### ISSUE TITLE
Możliwość wsparcia projektu na zasadzie Github Sponsors?

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#19]
Cześć,

Jako, że zgłaszam sporo requestów, czuje się w obowiązku zapytać czy jest możliwość wsparcia tego projektu.
Czy rozważasz dodanie Github Sponspor lub innej takiej opcji, aby można było wspierać projekt?

![image](https://github.com/user-attachments/assets/2d9bbecb-d2eb-4d2f-a154-863412b41bda)

**Comment by lkosson** [comment]
Nie przewiduję czerpania zysków z tej aplikacji - pośrednio ani bezpośrednio - ale jak będziesz potrzebował dedykowanego systemu, szczególnie z brażny logistycznej - odezwij się :-)

Jeśli bardzo chcesz przesłać jakiś datek, to odezwij się na priv to dam namiar na pewną fundację (z zupełnie innej brażny).
