### ISSUE TITLE
Dodanie wysłanie faktur poprzez e-mail

### ISSUE THREAD

**Issue by misiek75** [lkosson/profak#2]
Używam tego programu i uważam że jest świetny

Czy jest szansa aby dodać funkcję wysłania faktur poprzez e-mail w najbliższej przyszłości ?

**Comment by lkosson** [comment]
Jest szansa. Zobaczę, na co czas pozwoli.

**Comment by misiek75** [comment]
Ok czekam cierpliwe

**Comment by lkosson** [comment]
Dodałem obsługę wysyłki faktur e-mailem bezpośrednio z programu. Skompilujesz sobie samodzielnie wersję do testów, czy wystawić binarki?

**Comment by misiek75** [comment]
Świetnie. Skompiluje sobie sam

**Comment by lkosson** [comment]
Dodane w wersji 1.7.0.
