### ISSUE TITLE
Dodanie logo do faktury PDF

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#20]
Cześć,

Czy jest szansa na udostępnienie opcji dodania logo firmy do faktury?
Pewnie wymagało by to przeprojektowania wyglądu FV.
Mogę zaprojektować różne wizualizację z propozycjami jak mogło by to wyglądać

**Comment by lkosson** [comment]
W nieco dalszych planach mam przerobienie mechanizmu wydruków z obecnego Reporting Services na QuestPDF. Wtedy pewnie rozważę możliwość większego dostosowania wyglądu faktury do własnych potrzeb i/lub możliwość definiowania wydruku w całości po swojemu.

**Comment by kanlukasz** [comment]
Ok, dzięki za info.

Tylko delikatnie dopytam czy dalsze plany dotyczą realizacji jeszcze w 2024, czy to raczej bardziej odległe i skomplikowane zadanie? Pytam, bo od nowego roku planuję przenieść swoje firmy na ten program i już się do tego przygotowuję _(w obecnym programie mamy logo)_.

To niebywałe, ale zdarzają się kontrahenci, u których księgowość, widząc np., że logo było, a teraz go nie ma, potrafi wszcząć wielkie dochodzenie, czy to na pewno ta sama firma, mimo że mają przecież dane. 🥴
Wiem, że to brzmi kuriozalnie, ale serio znam takie przypadki ;-) 🤦‍♂️

Ewentualnie póki co napiszę coś w Pythonie co mi doda logo do już wydrukowanego PDFa z programu :)

Tak czy inaczej czekam cierpliwie i jeszcze raz bardzo Ci dziękuję za udostępnienie do używania tak świetnego programu 👏

**Comment by lkosson** [comment]
Raczej dłuższa perspektywa czasowa. Zadanie samo w sobie jest nie tyle skomplikowane, co żmudne i - w najlepszym wypadku - nie będzie miało żadnych widocznych rezultatów (a w najgorszym: po pół roku wyjdzie, że wszystkie wystawione faktury mają jakiegoś babola i trzeba to będzie odkręcać u klientów).

Na szybko mogę zaproponować, żebyś sobie sforkował repo i dopieścił wydruk faktury do własnych potrzeb. Nawet jeśli nie miałeś wcześniej do czynienia z Reporting Services, to edycja układu strony i dorzucenie tam logo nie powinno zająć więcej niż 15 minut. Jedyna nieoczywista rzecz to konieczność doinstalowania w Visual Studio rozszerzenia "Microsoft RDLC Report Designer", żeby móc edytować pliki RDLC w edytorze WYSIWYG.

**Comment by lkosson** [comment]
Zmiana mechanizmu wydruków jest bardziej odległa niż początkowo zakładałem. Jako rozwiązanie przejściowe dodałem funkcjonalność, by szablony wydruków były wczytywane z plików RDLC w katalogu z programem, o ile takie istnieją. Zatem jeśli potrzebujesz nieco przerobić szablon faktury, weź plik `Faktura.rdlc` z katalogu `Wydruki` z repo, dopieść po swojemu w microsoftowym edytorze i wrzuć do katalogu z EXEkiem.

**Comment by kanlukasz** [comment]
Super, to będzie w 100% wystarczające
Tylko teraz to testuje i wygląda tak, jak by nie wyłapywał w ogóle tego zmodyfikowanego pliku.

Kroki:

1. Pobrałem wersję 1.10 z repo

2. Pobrałem plik `https://github.com/lkosson/profak/blob/master/Wydruki/Faktura.rdlc`
3. Za pomocą [Microsoft Report Builder](https://www.microsoft.com/en-us/download/details.aspx?id=53613) zmodyfikowałem dla przykładu elementy:
    <img width="350" alt="Untitled" src="https://github.com/user-attachments/assets/064336e0-3cc3-4d2d-86d2-05cee6a67b13">

4. Wgrałem zmodyfikowany plik do katalogu z programem:
    ![image](https://github.com/user-attachments/assets/bbb7ff37-6c39-463d-bb58-5ad289421638)

5. Uruchomiłem program

6. Wygenerowałem testową fakturę

7. Kliknąłem `Drukuj`

8. I faktura wygląda normalnie, bez tych moich zmian

**Comment by lkosson** [comment]
W wersji `1.10.0` tego jeszcze nie ma. Chcę najpierw sprawdzić na lokalnej wersji czy nic się nie posypało i dopiero wtedy to wrzucić publicznie. Jeśli też chcesz przetestować, to dołączam binarki do podmiany:
[ProFak-1.10.1-beta1-20241203.zip](https://github.com/user-attachments/files/17991084/ProFak-1.10.1-beta1-20241203.zip)

**Comment by kanlukasz** [comment]
Ok dzięki, przetestowałem i z tego co widzę, działa super.
To świetne rozwiązanie. Bardzo bardzo dziękuję!

**Comment by lkosson** [comment]
W najbliższej wersji programu zmieni się nieco lista pól umieszczanych na wydruku - dotychczas zlepione w całość sekcje typu `DaneNabywcy` czy `Stopka` są rozbite na pojedyncze pola, a ich nagłówki dostępne do edycji w RDLC tak, żeby można było sobie swobodnie wyciąć lub zmienić poszczególne linijki:

![obraz](https://github.com/user-attachments/assets/bdeb7ced-1e55-4a6a-988f-395924486792)

W kolejnych aktualizacjach nie będzie już tak drastycznych zmian.

**Comment by lkosson** [comment]
Dodane w wersji 1.11.0.
