### ISSUE TITLE
Pole rabat na fakturze

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#23]
Cześć,

Czy jest to możliwe (i co o tym sądzisz), aby dodać kolumnę `rabat` na pozycjach na fakturze?
Czasem coś może być sprzedawane np. z rabatem 10% i fajnie to wygląda, gdy kontrahenci widzą wartość rabatu w %, cenę przed i cenę po, na pozycji w fakturze.

Oczywiście możemy wpisywać taką informację w uwagach, ale pomyślałem, że podzielę się taką sugestią.

**Comment by lkosson** [comment]
Ma sens. Dodam.

**Comment by lkosson** [comment]
Dodane w wersji 1.10.0.
