### ISSUE TITLE
Import danych

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#24]
Cześć,

Czy jestem w stanie zaimportować faktury sprzedażowe i zakupowe z poprzednich lat?
Domyślam się, że może to nie być takie proste bo dochodzą do tego jeszcze kontrahenci itd., ale może jest jakiś sposób/uproszczona opcja?

Ewentualnie czy mogę to zrobić bezpośrednio z poziomu bazy danych? W sensie jako sql `INSERT INTO Faktura (....`  ?
Masz może jakiś przykład albo mikro-dokumentacje, która ma rozpisane, jakie pola trzeba by obsłużyć w zapytaniu?

**Comment by lkosson** [comment]
Nie planowałem robić importu, bo zakładałem, że ProFak będzie pierwszym programem, z którego ktoś będzie korzystał prowadząc działalność i ewentualnie z czasem będzie przesiadać się na inne, bardziej rozbudowane rozwiązanie, niż na odwrót. W swoim przypadku migrowałem dane robiąc `INSERT`y bezpośrednio do bazy, ale generalnie nie polecam takiej metody, bo jest z tym dużo babrania, szczególnie z korektami.

Myślę, że sensownym kompromisem byłby import z `JPK_FA`. Praktycznie każdy program do fakturowania umożliwia wygenerowanie takiego zestawienia, jego struktura jest ustandaryzowana i regularna, a dodatkowo zawiera dane kontrahentów.

**Comment by lkosson** [comment]
Dodane w wersji 1.10.0.

**Comment by kanlukasz** [comment]
Cześć

A czy jestem w stanie zaimportować faktury zakupu?
`JPK_FA` zawiera tylko sprzedaż, a przy próbie importu `JPK_V7M` zwraca błąd. Pewnie nie obsługujesz struktury z V7M?
Ewentualnie jakieś jednorazowe obejście, które mogę zastosować?

**Comment by lkosson** [comment]
`JPK_V7M` zawiera tylko szczątkowe dane z nagłówków faktur (nie ma nawet rozbicia na pozycje faktury), więc w kontekście importu danych niewiele da. Technicznie nie ma przeszkód, by przez `JPK_FA` importować faktury zakupu, ale formalnie ten plik jest przeznaczony tylko dla sprzedaży i nie sądzę, by w jakiejkolwiek aplikacji dało się go wygenerować dla faktur zakupu.

ProFak potrafi zaimportować faktury (sprzedażowe i kosztowe) z XML KSeF, więc jeśli masz aplikację, która ma już integrację z KSeF i potrafi na żądanie wygenerować XML dla archiwalnych dokumentów, możesz w ten sposób je przenieść.

Jako ostateczność pozostaje ręczny import danych do bazy do tabel `Faktura` i `PozycjaFaktury`. Kolumny mają polskie, opisowe nazwy, więc powinno być jednoznaczne co ma gdzie trafić. Osobiście tego typu jednorazowe i niezbyt skomplikowane importy najczęściej robię przez Excela, tj. eksportuję z dotychczasowego programu zestawienie do postaci tabelarycznej (od biedy przez `CTRL-C` / `CTRL-V`), dodaję w arkuszu kolumnę z wyrażeniem postaci `="INSERT INTO Tabela (Kolumna1, Kolumna2) VALUES ('"&A1&"','"&B1&"')"` generującą szereg odpowiednich poleceń, które następnie uruchamiam bezpośrednio na bazie.
