### ISSUE TITLE
Kontrola duplikacji kontrahentów

### ISSUE THREAD

**Issue by MrFynn** [lkosson/profak#25]
Warto pomyśleć nad wprowadzeniem sprawdzania czy instnieje kontrahent o podobnych danych i/lub takim samym numerze NIP. Unikniemy w ten sposób powielania kartotek, jeśli ktoś używa programu schematem i dodaje automatycznie nowego kontrahenta przy każdej fakturze.

**Comment by lkosson** [comment]
Słuszna uwaga. Przygotowałem taką walidację; będzie uwzględnione w kolejnej wersji.

**Comment by lkosson** [comment]
Dodane w wersji 1.11.0.
