### ISSUE TITLE
Błąd w pobieraniu danych z GUS

### ISSUE THREAD

**Issue by xMikooo** [lkosson/profak#3]
Dzisiaj zauważyłem, że pobranie jakichkolwiek danych z GUS kończy się błędem. Najprawdopodobniej GUS zmienił format danych lub występuje błąd z pobraniem klucza. Postaram się sprawdzić co się dzieje w aplikacji i ewentualnie naprawić problem, jak się uda zrobię pull request.
![image](https://github.com/lkosson/profak/assets/55462052/f8251e81-1d71-438c-a697-ee671c65243c)

**Comment by xMikooo** [comment]
Usiadłem nad tym chwilę i doszedłem do wniosku, że GUS zmienił format danych, od teraz jest szyfrowany ich własną funkcją. Po wywolaniu `bd(dane)` w konsoli javascriptu otrzymujemy dane, które już są w starym formacie. Problemem jest, że ich funkcja jest obfuscated. Nie jestem, aż tak obeznany w javascripcie czy c#, żeby odwrócić tę funkcję i przepisać do c#, więc chyba poczekam na nową wersję programu rozwiązującą problem.

**Comment by lkosson** [comment]
Faktycznie, API zaczęło zwracać zaszyfrowane dane, a funkcja deszyfrująca jest zaciemniona. Zobaczę, co da się z tym zrobić.

**Comment by lkosson** [comment]
Poprawione w wersji 1.7.0.
