### ISSUE TITLE
Język i format daty

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#4]
Cześć,

---

 _Testuje Twój program bo właśnie szukam czegoś prostego do faktur co działa lokalnie.
Wygląda obiecująco, ale znalazłem kilka problemów. Otworzę kilka issues z tym co znalazłem.
Nie wiem na ile jesteś otwarty na obce issues. No ale jak coś to po prostu pozamykasz :-)_

---

Pierwsza sprawa, która rzuciła mi się w oczy to obsługa dat:
![image](https://github.com/user-attachments/assets/2f4796ba-9e01-4506-ac84-1256504418a2)

Używam Windowsa w j. angielskim. Zakładam, że profak pobiera date z systemu dlatego tak się wyświetla w programie?
Czy jest szansa, aby to mogło być definiowane przez program? Wolałbym w programie mieć to po polsku

Na fakturze też jest po angielsku. To tak średnio wygląda.
![image](https://github.com/user-attachments/assets/b0ad6346-571d-4f53-9158-ab13d2db08b8)
![image](https://github.com/user-attachments/assets/949da212-d426-4eff-857a-4b52ad11eeea)

**Comment by lkosson** [comment]
Cześć,

tak - profak korzysta z języka i formatów domyślnych dla systemu. Długo myślałem, czy to dobre rozwiązanie, ale stwierdziłem, że program nie będzie używany poza polskim rynkiem i zakładałem, że nawet na angielskim windowsie użytkownicy będą mieli wybrane polskie ustawienia regionalne.

To niepierwsza uwaga na temat anglojęzycznych słów w datach, więc tak - przy najbliższej okazji ustawię, by program posługiwał się polskimi nazwami, respektując ewentualne własnoręcznie ustawione w systemie formaty daty.

**Comment by lkosson** [comment]
Poprawione w wersji 1.8.0.

**Comment by kanlukasz** [comment]
To też teraz przetestowałem. Uruchomiłem od nowa na testowej bazie danych ale widzę, że daty nadal nie są w j. PL ani formacie PL
Widok wystawiania faktury:

![image](https://github.com/user-attachments/assets/5c13cebd-b69a-4c41-8ef0-5bc70b646046)

**Comment by lkosson** [comment]
Faktycznie, ta kontrolka ignoruje ustawienia aplikacji i zawsze korzysta z ustawień systemowych. Zmienię odgórnie format dat na taki, który nie zawiera tekstowych nazw miesięcy i dni tygodnia.

**Comment by kanlukasz** [comment]
Super, dziękuje. Ogólnie jeżeli mogę zasugerować, może najlepszy byłby po prostu ujednolicony format dat - zgodnie z tym jak masz na listingu faktur:

czyli `YYYY-MM-DD`

![image](https://github.com/user-attachments/assets/0c14515f-6f5f-4b85-9be0-e286a7262eb4)

**Comment by lkosson** [comment]
W przyszłości wyciągnę format daty do konfiguracji programu, ale póki co niech będzie stały `YYYY-MM-DD`. Dużo bardziej wolę, żeby program korzystał z systemowych ustawień regionalnych, ale Microsoft nie ułatwia sprawy chowając głęboko w panelu sterowania możliwość zmiany formatu daty i dodatkowo proponując domyślny format `DD.MM.YYYY`.

Sprawdzisz czy po tej poprawce - [profak-1.8.0-fix-20241005.zip](https://github.com/user-attachments/files/17265176/profak-1.8.0-fix-20241005.zip) - format dat jest spójny na spisach, formatkach i wydrukach na Twoim systemie?

**Comment by kanlukasz** [comment]
Przetestowałem, teraz jest perfekcyjnie. Dzięki za szybki fix!

PS. Uważam ten program za rewelacyjny. Postaram się porobić jeszcze jakieś ogólne testy i podzielę się ewentualnymi uwagami/pomysłami. Może to pomoże w rozwoju apki.

PS2. Przepraszam za brak pull requestów z mojej strony, ale na co dzień siedzę w PHP i nie mam na tyle doświadczenia w C#, aby zrobić sensownego pull'a.

Pozdrawiam ✌️

**Comment by lkosson** [comment]
Miło to słyszeć. Jak coś jeszcze znajdziesz - zgłaszaj.

**Comment by lkosson** [comment]
Poprawione w wersji 1.8.1.
