### ISSUE TITLE
Ucięte widoki

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#5]
Cześć ponownie,
W kilku miejscach widzę ucięte widoki. Czy da radę coś z tym zrobić?

Np:

### Nowa pozycja na fv:
![image](https://github.com/user-attachments/assets/552914d1-e525-48bc-b590-fe778190e6b9)

### Po kliknięciu na `Dodaj wpłatę` (resize okienka nie pomaga, wraca do tego samego stanu):
![image](https://github.com/user-attachments/assets/aa8b4a73-e835-45da-ade7-cdabc6c28b29)

### Widok `Wystaw fakturę`
![image](https://github.com/user-attachments/assets/3a99d6c1-17f7-4c62-b615-ec9ad3424981)

#### Mój OS:
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
```

#### Dodatkowe info:
Nie wiem czy ma to znaczenie, ale pracuje w 4K na 27", 150% powiększenie w ustawieniach Windowsa (zalecane)

**Comment by lkosson** [comment]
To zdecydowanie kwestia powiększenia na 150% - WinForms kiepsko współpracuje z wysokim DPI. Zobaczę co da się z tym zrobić.

**Comment by lkosson** [comment]
Poprawione w wersji 1.8.0.
