### ISSUE TITLE
Kolumna Uwagi?

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#6]
Czy jest możliwość dodania kolumny Uwagi na liście faktur?
![image](https://github.com/user-attachments/assets/1410fc7e-579d-4273-8220-f622de3616b3)

Chodzi mi o wyświetlanie uwag z tych pól:
![image](https://github.com/user-attachments/assets/fb24d3b3-a089-483b-877f-f6482500a57b)

**Comment by lkosson** [comment]
Zmiana sama w sobie jest prosta, ale nieco koliduje z przyjętym założeniem, by w spisach nie było konieczne używanie poziomego scrollbara, a wartości w tych kolumnach potencjalnie mogą być dość długie. Najfajniej pewnie byłoby dać możliwość własnoręcznego wyboru zestawu widocznych kolumn, ale z tym będzie ciut więcej roboty.

Tak czy inaczej - wrzucę do backloga.

**Comment by lkosson** [comment]
Dodane w wersji 1.8.0.
