### ISSUE TITLE
Zapamiętywanie ostatniego stanu drzewka w menu

### ISSUE THREAD

**Issue by kanlukasz** [lkosson/profak#9]
Cześć,

Po ponownym uruchomieniu programu, drzewko menu nie zapamiętuje pozycji w jakich było pozwijane.
np. ustawiam widoczność menu tak, aby było dla mnie wygodnie pracować i wykonywać powtarzalne czynności.

### Ustawiam widoczność menu wg. swoich preferencji:
![image](https://github.com/user-attachments/assets/1fd3383b-12e9-4996-b31a-77d49c688fe1)

### Gdy uruchomię program ponownie, drzewko menu znowu "resetuje się" wygląda tak:
![image](https://github.com/user-attachments/assets/2dded7a0-bafa-40ca-b6aa-55b3e6957421)

Czy da się wprowadzić możliwość, aby zapamiętywał się ostatni stan menu?

Alternatywnie: czy można wprowadzić przycisk `Zwiń wszystko` ?

**Comment by lkosson** [comment]
Ma sens. Dodam zapamiętywanie stanu rozwinięcia drzewka.

**Comment by lkosson** [comment]
Dodane w wersji 1.9.0.
